var app = angular.module("Panorama", []);
app.controller("artistCtrl",function($scope){
	$scope.artistes=[
	{
		name:'KAYTRANADA',
		jour:'VENDREDI 3 AVRIL',
		jourId:'1',
		heure:'19h20',
        heureId:19,
		style:'AUCUN/STYLE',
		description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis fermentum enim, ut pulvinar lacus interdum vitae. Curabitur ultrices, nibh in auctor tincidunt, neque sapien fermentum dolor, in convallis augue quam vel mauris. Duis mollis sollicitudin nulla placerat fermentum. Nunc ipsum ex, condimentum a ante sed, congue pulvinar leo. Cras dignissim, justo ut ultrices ultricies, mauris ligula malesuada leo, fermentum varius purus nulla volutpat est. Duis purus eros, dictum sit amet commodo in, ullamcorper a magna. Ut sit amet feugiat ligula. Sed sagittis massa dignissim, convallis nisi nec, placerat erat.',
		club:'Grand Hall',
        salleId:'1',
		pic_link_black:'images/artistes/kay.jpg',
		pic_link_color:'images/artistes/kay_c.jpg',
		vid_link:'https://www.youtube.com/watch?v=z1BVZ0PMs9M',
		twitter:'#',
		facebook:'#',
		soundcloud:'#'
	},	 	
	{
		name:'KAYTRANADA',
		jour:'VENDREDI 3 AVRIL',
		jourId:'1',
        salleId:'2',
		heure:'21h20',
        heureId:21,
		style:'AUCUN/STYLE',
		description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis fermentum enim, ut pulvinar lacus interdum vitae. Curabitur ultrices, nibh in auctor tincidunt, neque sapien fermentum dolor, in convallis augue quam vel mauris. Duis mollis sollicitudin nulla placerat fermentum. Nunc ipsum ex, condimentum a ante sed, congue pulvinar leo. Cras dignissim, justo ut ultrices ultricies, mauris ligula malesuada leo, fermentum varius purus nulla volutpat est. Duis purus eros, dictum sit amet commodo in, ullamcorper a magna. Ut sit amet feugiat ligula. Sed sagittis massa dignissim, convallis nisi nec, placerat erat.',
		club:'Grand Hall',
		pic_link_black:'images/artistes/kay.jpg',
		pic_link_color:'images/artistes/kay_c.jpg',
		vid_link:'https://www.youtube.com/watch?v=z1BVZ0PMs9M',
		twitter:'#',
		facebook:'#',
		soundcloud:'#'
	},
	{
		name:'KAYTRANADA',
		jour:'VENDREDI 3 AVRIL',
		jourId:'1',
        salleId:'3',
		heure:'23h20',
        heureId:23,
		style:'AUCUN/STYLE',
		description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis fermentum enim, ut pulvinar lacus interdum vitae. Curabitur ultrices, nibh in auctor tincidunt, neque sapien fermentum dolor, in convallis augue quam vel mauris. Duis mollis sollicitudin nulla placerat fermentum. Nunc ipsum ex, condimentum a ante sed, congue pulvinar leo. Cras dignissim, justo ut ultrices ultricies, mauris ligula malesuada leo, fermentum varius purus nulla volutpat est. Duis purus eros, dictum sit amet commodo in, ullamcorper a magna. Ut sit amet feugiat ligula. Sed sagittis massa dignissim, convallis nisi nec, placerat erat.',
		club:'Grand Hall',
		pic_link_black:'images/artistes/kay.jpg',
		pic_link_color:'images/artistes/kay_c.jpg',
		vid_link:'https://www.youtube.com/watch?v=z1BVZ0PMs9M',
		twitter:'#',
		facebook:'#',
		soundcloud:'#'
	},	 	
	{
		name:'KAYTRANADA',
		jour:'VENDREDI 3 AVRIL',
		jourId:'2',
		heure:'23h20',
        heureId:23,
		style:'AUCUN/STYLE',
		description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis fermentum enim, ut pulvinar lacus interdum vitae. Curabitur ultrices, nibh in auctor tincidunt, neque sapien fermentum dolor, in convallis augue quam vel mauris. Duis mollis sollicitudin nulla placerat fermentum. Nunc ipsum ex, condimentum a ante sed, congue pulvinar leo. Cras dignissim, justo ut ultrices ultricies, mauris ligula malesuada leo, fermentum varius purus nulla volutpat est. Duis purus eros, dictum sit amet commodo in, ullamcorper a magna. Ut sit amet feugiat ligula. Sed sagittis massa dignissim, convallis nisi nec, placerat erat.',
		club:'Grand Hall',
        salleId:'4',
		pic_link_black:'images/artistes/kay.jpg',
		pic_link_color:'images/artistes/kay_c.jpg',
		vid_link:'https://www.youtube.com/watch?v=z1BVZ0PMs9M',
		twitter:'#',
		facebook:'#',
		soundcloud:'#'
	},
	{
		name:'KAYTRANADA',
		jour:'VENDREDI 3 AVRIL',
		jourId:'3',
		heure:'00h20',
        heureId:0,
		style:'AUCUN/STYLE',
		description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis fermentum enim, ut pulvinar lacus interdum vitae. Curabitur ultrices, nibh in auctor tincidunt, neque sapien fermentum dolor, in convallis augue quam vel mauris. Duis mollis sollicitudin nulla placerat fermentum. Nunc ipsum ex, condimentum a ante sed, congue pulvinar leo. Cras dignissim, justo ut ultrices ultricies, mauris ligula malesuada leo, fermentum varius purus nulla volutpat est. Duis purus eros, dictum sit amet commodo in, ullamcorper a magna. Ut sit amet feugiat ligula. Sed sagittis massa dignissim, convallis nisi nec, placerat erat.',
		club:'Grand Hall',
        salleId:'2',
		pic_link_black:'images/artistes/kay.jpg',
		pic_link_color:'images/artistes/kay_c.jpg',
		vid_link:'https://www.youtube.com/watch?v=z1BVZ0PMs9M',
		twitter:'#',
		facebook:'#',
		soundcloud:'#'
	},	 	
	{
		name:'KAYTRANADA',
		jour:'VENDREDI 3 AVRIL',
		jourId:'2',
		heure:'20h20',
        heureId:20,
		style:'AUCUN/STYLE',
		description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis fermentum enim, ut pulvinar lacus interdum vitae. Curabitur ultrices, nibh in auctor tincidunt, neque sapien fermentum dolor, in convallis augue quam vel mauris. Duis mollis sollicitudin nulla placerat fermentum. Nunc ipsum ex, condimentum a ante sed, congue pulvinar leo. Cras dignissim, justo ut ultrices ultricies, mauris ligula malesuada leo, fermentum varius purus nulla volutpat est. Duis purus eros, dictum sit amet commodo in, ullamcorper a magna. Ut sit amet feugiat ligula. Sed sagittis massa dignissim, convallis nisi nec, placerat erat.',
		club:'Grand Hall',
        salleId:'1',
		pic_link_black:'images/artistes/kay.jpg',
		pic_link_color:'images/artistes/kay_c.jpg',
		vid_link:'https://www.youtube.com/watch?v=z1BVZ0PMs9M',
		twitter:'#',
		facebook:'#',
		soundcloud:'#'
	}
	];
});


app.controller("PanoCtrl",function($scope) {
	$scope.artiste = [
	
  {
    'id':null,
    'jour':'1',
    'heure':'21h00',
    'ordre_passage':2,
    'name':'DON RIMINI B2B SURFING LEONS',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'z1BVZ0PMs9M',
    'facebook':'https://www.facebook.com/donrimini?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':null,
    'jour':'1',
    'heure':'22h40',
    'ordre_passage':5,
    'name':'LOUIE P',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'XWtIdL1U6iE',
    'facebook':'https://www.facebook.com/pages/Louie-P-Celestic/115799631828171?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':1,
    'jour':'1',
    'heure':'23h20',
    'ordre_passage':8,
    'name':'KAYTRANADA',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'0ymI54DuMj8',
    'facebook':'https://www.facebook.com/Kaytranada?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'Louis Kevin Celestin est un canadien ; né à Haïti ; à 22 ans et est le nouveau Producteur et DJ en vogue. Ses morceaux ; mélange d influences Hip Hop et RnB avec des sonorités très électroniques actuelles. Il sera un des grands temps fort de Panoramas pour cette 18ème édition. Première date en Bretagne. ',
    'pic_link_black':'images/artistes/1.jpg',
    'pic_link_color':'images/artistes/1_c.jpg'
  },
  {
    'id':2,
    'jour':'1',
    'heure':'00h35',
    'ordre_passage':11,
    'name':'THE BLOODY BEETROOTS DJ SET',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'JqLSn5i6CeQ',
    'facebook':'https://www.facebook.com/thebloodybeetroots?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'Sous le patronyme SBCR se cache Bob Rifo ; leader des Bloody Beetroots qui nous fait la gentillesse de revenir nous présenter un DJ set hyper efficace pour nos 18 ans. ',
    'pic_link_black':'images/artistes/2.jpg',
    'pic_link_color':'images/artistes/2_c.jpg'
  },
  {
    'id':3,
    'jour':'1',
    'heure':'02h05',
    'ordre_passage':14,
    'name':'INFECTED MUSHROOM',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'wQ3bJN1zLKw',
    'facebook':'https://www.facebook.com/infectedmushroom?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/3.jpg',
    'pic_link_color':'images/artistes/3_c.jpg'
  },
  {
    'id':5,
    'jour':'1',
    'heure':'03h35',
    'ordre_passage':17,
    'name':'BORIS BREJCHA',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'uUQ8Wgqayp4',
    'facebook':'https://www.facebook.com/BorisBrejcha.Official?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'Linventeur de la \'High Tech Minimal\' est un allemand surdoué ; véritable référence au sein du milieu techno. C est un grand plaisir pour notre équipe de le recevoir à nouveau à Lango pour un set qui s annonce \'anthologique\' pour fêter avec lui nos 18 ans. ',
    'pic_link_black':'images/artistes/5.jpg',
    'pic_link_color':'images/artistes/5_c.jpg'
  },
  {
    'id':15,
    'jour':'1',
    'heure':'20h00',
    'ordre_passage':1,
    'name':'MMMMM',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'UT3S85Ovw8o',
    'facebook':'https://www.facebook.com/mmmmmtheband?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/15.jpg',
    'pic_link_color':'images/artistes/15_c.jpg'
  },
  {
    'id':null,
    'jour':'1',
    'heure':'21h20',
    'ordre_passage':4,
    'name':'SALUT C EST COOL',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'Kxa8PIw4LfI',
    'facebook':'https://www.facebook.com/salutcestcool?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':null,
    'jour':'1',
    'heure':'22h40',
    'ordre_passage':6,
    'name':'JOKE',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'XgpLF0Qvh9M',
    'facebook':'https://www.facebook.com/the.jokejoke?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':null,
    'jour':'1',
    'heure':'00h00',
    'ordre_passage':9,
    'name':'NOISIA',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'SAO-lzl3vVQ',
    'facebook':'https://www.facebook.com/noisia?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'Original ; émotionnel et viscéral sont les 3 mots qui reviennent pour parler de la musique de Noisia. Les 3 gars de Groningen (NL) sont les symboles de la Bass Music actuelle. Ce sera leur première fois à Panoramas ; ce qui représente un véritable évènement pour notre festival. ',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':null,
    'jour':'1',
    'heure':'01h30',
    'ordre_passage':12,
    'name':'SAVANT',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'IFM4qahWo6E',
    'facebook':'https://www.facebook.com/SavantOfficial?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':11,
    'jour':'1',
    'heure':'03h00',
    'ordre_passage':15,
    'name':'FAR TOO LOUD',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'VlnBh0hRpfM',
    'facebook':'https://www.facebook.com/fartooloud?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/11.jpg',
    'pic_link_color':'images/artistes/11_c.jpg'
  },
  {
    'id':17,
    'jour':'1',
    'heure':'22h00',
    'ordre_passage':3,
    'name':'BLUTCH',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'Sr1l4OVQMmo',
    'facebook':'https://www.facebook.com/pages/Blutch/333167113396807?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/17.jpg',
    'pic_link_color':'images/artistes/17_c.jpg'
  },
  {
    'id':16,
    'jour':'1',
    'heure':'23h00',
    'ordre_passage':7,
    'name':'MIDSIDE',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'_HqV-ZSohJU',
    'facebook':'https://www.facebook.com/musicmidside?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/16.jpg',
    'pic_link_color':'images/artistes/16_c.jpg'
  },
  {
    'id':null,
    'jour':'1',
    'heure':'00h15',
    'ordre_passage':10,
    'name':'LIDO',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'1_WeBcBeuWU',
    'facebook':'https://www.facebook.com/Lidogotsongs?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':14,
    'jour':'1',
    'heure':'01h45',
    'ordre_passage':13,
    'name':'STWO',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'dxNv92VOO_I',
    'facebook':'https://www.facebook.com/StwoFR?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/14.jpg',
    'pic_link_color':'images/artistes/14_c.jpg'
  },
  {
    'id':10,
    'jour':'1',
    'heure':'03h15',
    'ordre_passage':16,
    'name':'KINK LIVE',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'-0MoCENw8OQ',
    'facebook':'https://www.facebook.com/kink303?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/10.jpg',
    'pic_link_color':'images/artistes/10_c.jpg'
  },
  {
    'id':34,
    'jour':'2',
    'heure':'20h30',
    'ordre_passage':2,
    'name':'DBFC',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'xbS_wO1_nLQ',
    'facebook':'https://www.facebook.com/DBFCtheband?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/34.jpg',
    'pic_link_color':'images/artistes/34_c.jpg'
  },
  {
    'id':null,
    'jour':'2',
    'heure':'22h00',
    'ordre_passage':4,
    'name':'SUPER DISCOUNT 3',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'hc0S9Qg9Imc',
    'facebook':'https://www.facebook.com/EtienneDeCrecyNetwork?fref=ts&rf=110357905651814',
    'twitter':'',
    'soundcloud':'',
    'description':'Il s agit ici du projet Live d Étienne De Crécy ; Alex Gopher & Julien Delfaud. Ce projet est un génèse de l évolution des musiques électroniques ; plus \'house et funky\' que les précédents. C est un véritable show à 6 mainsintense qui nous attend le 2.',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':20,
    'jour':'2',
    'heure':'23h20',
    'ordre_passage':7,
    'name':'BRODINSKI',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'VQu-rJEoYQY',
    'facebook':'https://www.facebook.com/brodinski?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/20.jpg',
    'pic_link_color':'images/artistes/20_c.jpg'
  },
  {
    'id':null,
    'jour':'2',
    'heure':'00h50',
    'ordre_passage':10,
    'name':'TCHAMI',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'z5ZdjwbQnXc',
    'facebook':'https://www.facebook.com/iamTchami?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':18,
    'jour':'2',
    'heure':'02h20',
    'ordre_passage':12,
    'name':'LAURENT GARNIER',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'MA0qWtiXFFo',
    'facebook':'https://www.facebook.com/laurentgarnierofficial?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'Le pape de la techno française. Il a survécu à toutes les époques et courants et est un modèle pour la nouvelle génération. Ses sets sont à chaque fois des évènements hyper attendus.',
    'pic_link_black':'images/artistes/18.jpg',
    'pic_link_color':'images/artistes/18_c.jpg'
  },
  {
    'id':null,
    'jour':'2',
    'heure':'04h20',
    'ordre_passage':15,
    'name':'TALE OF US',
    'style':'',
    'isChecked':false,
    'salle':'Grand Hall',
    'youtube':'p7MZAPEXbPo',
    'facebook':'https://www.facebook.com/TaleOfUs?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'Ces 2 DJ ont pris cette année une ampleur exceptionnelle au point d en faire des têtes d affiche de Panoramas#18. Ils ont été élu par Resident Advisor #2ème meilleurs groupe techno au monde pour 2014. ',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':null,
    'jour':'2',
    'heure':'20h00',
    'ordre_passage':1,
    'name':'FALABELLA',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'TravJxyeXeo',
    'facebook':'https://www.facebook.com/FalabellaMusic?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':30,
    'jour':'2',
    'heure':'21h20',
    'ordre_passage':3,
    'name':'COELY',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'m3f8-oxLXr8',
    'facebook':'https://www.facebook.com/Coely?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/30.jpg',
    'pic_link_color':'images/artistes/30_c.jpg'
  },
  {
    'id':null,
    'jour':'2',
    'heure':'22h30',
    'ordre_passage':5,
    'name':'SUPERPOZE',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'rTz26pKS4A8',
    'facebook':'https://www.facebook.com/SuperpozeMusic?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':29,
    'jour':'2',
    'heure':'00h00',
    'ordre_passage':8,
    'name':'JOACHIM PASTOR',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'uO3lN-hugaQ',
    'facebook':'https://www.facebook.com/JoachimPastor?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/29.jpg',
    'pic_link_color':'images/artistes/29_c.jpg'
  },
  {
    'id':23,
    'jour':'2',
    'heure':'01h30',
    'ordre_passage':10,
    'name':'MOD3RN',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'m5B9B9sZ9hA',
    'facebook':'https://www.facebook.com/pages/M%C3%B6d3rn/170692996426386?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/23.jpg',
    'pic_link_color':'images/artistes/23_c.jpg'
  },
  {
    'id':24,
    'jour':'2',
    'heure':'03h30',
    'ordre_passage':14,
    'name':'MAX COOPER',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'KHQDGohpBsQ',
    'facebook':'https://www.facebook.com/maxcoopermax?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/24.jpg',
    'pic_link_color':'images/artistes/24_c.jpg'
  },
  {
    'id':27,
    'jour':'2',
    'heure':'05h00',
    'ordre_passage':16,
    'name':'ALESIA',
    'style':'',
    'isChecked':false,
    'salle':'Sésame',
    'youtube':'M0wWYKfl-Q8',
    'facebook':'https://www.facebook.com/alesia14thstreet?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/27.jpg',
    'pic_link_color':'images/artistes/27_c.jpg'
  },
  {
    'id':33,
    'jour':'2',
    'heure':'22h00',
    'ordre_passage':4,
    'name':'COTTON CLAW',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'EyRpVITtDxk',
    'facebook':'https://www.facebook.com/CottonClaw?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/33.jpg',
    'pic_link_color':'images/artistes/33_c.jpg'
  },
  {
    'id':26,
    'jour':'2',
    'heure':'23h00',
    'ordre_passage':6,
    'name':'FKJ LIVE',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'ftLxvw_eFN0',
    'facebook':'https://www.facebook.com/frenchkiwijuice?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/26.jpg',
    'pic_link_color':'images/artistes/26_c.jpg'
  },
  {
    'id':28,
    'jour':'2',
    'heure':'00h00',
    'ordre_passage':9,
    'name':'POINT POINT',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'WtM8uOifd2c',
    'facebook':'https://www.facebook.com/pointpointparis?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/28.jpg',
    'pic_link_color':'images/artistes/28_c.jpg'
  },
  {
    'id':31,
    'jour':'2',
    'heure':'01h30',
    'ordre_passage':11,
    'name':'THE GEEK & VRV',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'qlS_q3ywnN4',
    'facebook':'https://www.facebook.com/thegeekxvrv?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/31.jpg',
    'pic_link_color':'images/artistes/31_c.jpg'
  },
  {
    'id':null,
    'jour':'2',
    'heure':'03h00',
    'ordre_passage':13,
    'name':'MADBEN CYNETICS',
    'style':'',
    'isChecked':false,
    'salle':'Chapiteau',
    'youtube':'t9ZgvVnjHds',
    'facebook':'https://www.facebook.com/madbenofficial?ref=ts&fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':39,
    'jour':'3',
    'heure':'21h00',
    'ordre_passage':1,
    'name':'BRÜLIN',
    'style':'',
    'isChecked':false,
    'salle':'Coatelan',
    'youtube':'NOVID',
    'facebook':'https://www.facebook.com/brulinmusic?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/39.jpg',
    'pic_link_color':'images/artistes/39_c.jpg'
  },
  {
    'id':38,
    'jour':'3',
    'heure':'22h20',
    'ordre_passage':2,
    'name':'FLAVIEN BERGER',
    'style':'',
    'isChecked':false,
    'salle':'Coatelan',
    'youtube':'vrQxXjzkIFU',
    'facebook':'https://www.facebook.com/pages/Flavien-Berger/345609982248978?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/38.jpg',
    'pic_link_color':'images/artistes/38_c.jpg'
  },
  {
    'id':40,
    'jour':'3',
    'heure':'23h50',
    'ordre_passage':3,
    'name':'DDDXIE',
    'style':'',
    'isChecked':false,
    'salle':'Coatelan',
    'youtube':'sw1U9ylqJ4k',
    'facebook':'https://www.facebook.com/DDDXIE?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/40.jpg',
    'pic_link_color':'images/artistes/40_c.jpg'
  },
  {
    'id':null,
    'jour':'3',
    'heure':'01h20',
    'ordre_passage':4,
    'name':'RECONDITE',
    'style':'',
    'isChecked':false,
    'salle':'Coatelan',
    'youtube':'KKYYAbGpw6A',
    'facebook':'https://www.facebook.com/ReconditeMusic?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/.jpg',
    'pic_link_color':'images/artistes/_c.jpg'
  },
  {
    'id':37,
    'jour':'3',
    'heure':'02h50',
    'ordre_passage':5,
    'name':'ONIRIS',
    'style':'',
    'isChecked':false,
    'salle':'Coatelan',
    'youtube':'Qtj7_G-z2gw',
    'facebook':'https://www.facebook.com/onirisdj?fref=ts',
    'twitter':'',
    'soundcloud':'',
    'description':'0',
    'pic_link_black':'images/artistes/37.jpg',
    'pic_link_color':'images/artistes/37_c.jpg'
  }
];
	$scope.artisteNotIncludes = [];
	angular.copy($scope.artiste, $scope.artisteNotIncludes);
	$scope.artisteIncludes = [];

	$scope.cpt = [0,0,0];


	$scope.includeArtiste = function(artiste) {

		var i = $.inArray(artiste, $scope.artisteIncludes);
		if (i > -1) {
			$scope.cpt[artiste.jour - 1]--;
			artiste.isChecked = false;
			$scope.artisteIncludes.splice(i, 1);
			$scope.artisteNotIncludes.push(artiste);
		} else {
			$scope.cpt[artiste.jour - 1]++;
			artiste.isChecked = true;
			$scope.artisteIncludes.push(artiste);
			$scope.artisteNotIncludes.splice($.inArray(artiste, $scope.artisteNotIncludes), 1);
		}

	} 

	$scope.artisteFilter = function(artiste) {
		if ($scope.artisteIncludes.length >= 0) {
			if ($.inArray(artiste, $scope.artisteIncludes) < 0)
				return;
		}

		return artiste;
	}

	$scope.dayChecked  = function() {
        return $scope.day_pano;
    }

	$scope.dayFilter = function(artiste) {
		if (artiste.jour == $scope.day_pano)
			return artiste;
		else
			return;
	}

	$scope.change = function(artiste) {
		artiste.isChecked=true;
	} 

	$scope.calculatePosition = function() {
		
	}
});